version: "3"

networks:
  rmoff_kafka:
    name: rmoff_kafka

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    networks:
      - rmoff_kafka
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  broker:
    image: 'bitnami/kafka:latest'
    networks:
      - rmoff_kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://broker:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

#  producer:
#    #Uses an image that’s built from the Dockerfile in the current directory.
#    image: producer
#    #build: .
#    depends_on:
#      - broker
#    networks:
#      - rmoff_kafka

  consumer:
    #Uses an image that’s built from the Dockerfile in the current directory.
    image: consumer
    #build: .
    depends_on:
      - broker
    networks:
      - rmoff_kafka


#Service in docker-compose share same network


#docker build -t producer .
#docker run --network=rmoff_kafka --rm --name producer producer